const MANIFEST: &str = include_str!("../Cargo.toml");
const DIST_CONFIG: &str = include_str!("../dist-workspace.toml");
const RELEASE_WORKFLOW: &str = include_str!("../.github/workflows/release.yml");
const README: &str = include_str!("../README.md");
const JAPANESE_README: &str = include_str!("../README.ja.md");

const RELEASE_TARGETS: [&str; 4] = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
];

#[test]
fn distribution_is_reproducibly_pinned_for_the_prerelease() {
    // Cargo publication remains owner-gated, so dist must be explicitly
    // opted in instead of inferring eligibility from `publish`.
    for requirement in ["version = \"0.1.0-pre.1\"", "dist = true"] {
        assert!(
            MANIFEST.contains(requirement),
            "missing package distribution contract: {requirement}"
        );
    }

    for requirement in [
        "cargo-dist-version = \"0.31.0\"",
        "ci = \"github\"",
        "installers = [\"shell\", \"powershell\"]",
        "checksum = \"sha256\"",
        "pr-run-mode = \"skip\"",
    ] {
        assert!(
            DIST_CONFIG.contains(requirement),
            "missing distribution contract: {requirement}"
        );
    }

    for target in RELEASE_TARGETS {
        assert!(
            DIST_CONFIG.contains(target),
            "missing release target: {target}"
        );
    }

    assert!(!DIST_CONFIG.contains("aarch64-unknown-linux-gnu"));

    for action in [
        "actions/checkout",
        "actions/upload-artifact",
        "actions/download-artifact",
    ] {
        assert!(
            DIST_CONFIG.contains(action),
            "release Action must be commit-pinned: {action}"
        );
    }
}

#[test]
fn generated_release_workflow_has_no_branch_or_pull_request_trigger() {
    assert!(RELEASE_WORKFLOW.contains("This file was autogenerated by dist"));
    assert!(RELEASE_WORKFLOW.contains("tags:"));
    assert!(RELEASE_WORKFLOW.contains("'**[0-9]+.[0-9]+.[0-9]+*'"));
    assert!(!RELEASE_WORKFLOW.contains("branches:"));
    assert!(!RELEASE_WORKFLOW.contains("pull_request:"));
    assert!(!RELEASE_WORKFLOW.contains("workflow_dispatch:"));
    assert!(RELEASE_WORKFLOW.contains("permissions:\n  \"contents\": \"read\""));
    assert!(RELEASE_WORKFLOW.contains(
        "host:\n    # Only the job that creates the GitHub Release receives write access."
    ));
    assert!(RELEASE_WORKFLOW.contains("permissions:\n      \"contents\": \"write\"\n    needs:"));
    assert!(RELEASE_WORKFLOW.contains("environment: release"));
    assert!(RELEASE_WORKFLOW.contains("Validate release tag and main ancestry"));
    assert!(RELEASE_WORKFLOW.contains("git merge-base --is-ancestor"));
    assert!(!RELEASE_WORKFLOW.contains("cargo-dist-installer.sh | sh"));
    assert!(!RELEASE_WORKFLOW.contains("matrix.install_dist.run"));
    for digest in [
        "decb01c64c12501931c3cac3111b368a7f48adf8d9e65455c08e5757b9a1fd6f",
        "fd4d8f9f07802359cbcdc52bac3abd7d5201c4b73a7cbcdd6faca2232a389f0c",
        "cd355dab0b4c02fb59038fef87655550021d07f45f1d82f947a34ef98560abb8",
        "a14e17557b269b101405e0cc6b647581d56313c954a51c7fddd423bba21e17b2",
    ] {
        assert!(
            RELEASE_WORKFLOW.contains(digest),
            "cargo-dist archive must be digest-pinned: {digest}"
        );
    }
    for floating_action in [
        "actions/checkout@v",
        "actions/upload-artifact@v",
        "actions/download-artifact@v",
    ] {
        assert!(
            !RELEASE_WORKFLOW.contains(floating_action),
            "generated workflow must not use floating Action tag: {floating_action}"
        );
    }
}

#[test]
fn both_readmes_offer_installer_checksum_and_source_fallback_paths() {
    for readme in [README, JAPANESE_README] {
        for requirement in [
            "## Install",
            "qzt-installer.sh",
            "v0.1.0-pre.1",
            ".sha256",
            "set -eu",
            "shasum -a 256",
            "Get-FileHash -Algorithm SHA256",
            "cargo install --git https://github.com/albert-einshutoin/qzt --tag v0.1.0-pre.1 --locked",
        ] {
            assert!(
                readme.contains(requirement),
                "README is missing install requirement: {requirement}"
            );
        }
    }
}
