[package]
name = "qzt-fuzz"
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
qzt = { path = "..", version = "=0.1.0-pre.3", features = ["internal-testing"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "open_verify"
path = "fuzz_targets/open_verify.rs"
test = false
doc = false
bench = false

[[bin]]
name = "qzi_search"
path = "fuzz_targets/qzi_search.rs"
test = false
doc = false
bench = false

[[bin]]
name = "dli_decode"
path = "fuzz_targets/dli_decode.rs"
test = false
doc = false
bench = false
